#!/bin/bash

sudo apt-get update
sudo add-apt-repository universe
sudo apt-get -y install git salt-minion

echo 'master: 207.154.246.100 \n id: worker-slave' + $((RANDOM%1000)) |sudo tee /etc/salt/minion

setxkbmap fi

sudo systemctl restart salt-minion






